# CAGE coverage for each siRNA-KD replicate
bash ./scripts/get_coverage.sh ASCL1-Start.bed ASCL1_2_batch1A_rep1.ctss.bed ASCL1_2_batch1A_rep2.ctss.bed ASCL1_2_batch1A_rep3.ctss.bed ASCL1_2_batch1A
bash ./scripts/get_coverage.sh DACH1-Start.bed DACH1_2_batch1A_rep1.ctss.bed DACH1_2_batch1A_rep2.ctss.bed DACH1_2_batch1A_rep3.ctss.bed DACH1
bash ./scripts/get_coverage.sh GTF3A-Start.bed GTF3A_batch1A_rep1.ctss.bed GTF3A_batch1A_rep2.ctss.bed GTF3A_batch1A_rep3.ctss.bed GTF3A
bash ./scripts/get_coverage.sh HMGA1-Start.bed HMGA1_batch1A_rep1.ctss.bed HMGA1_batch1A_rep2.ctss.bed HMGA1_batch1A_rep3.ctss.bed HMGA1
bash ./scripts/get_coverage.sh HMGB2-Start.bed HMGB2_batch1A_rep1.ctss.bed HMGB2_batch1A_rep2.ctss.bed HMGB2_batch1A_rep3.ctss.bed HMGB2
bash ./scripts/get_coverage.sh HOPX-Start.bed HOPX_batch1A_rep1.ctss.bed HOPX_batch1A_rep2.ctss.bed HOPX_batch1A_rep3.ctss.bed HOPX
bash ./scripts/get_coverage.sh MLXIPL-Start.bed MLXIPL_batch1A_rep1.ctss.bed MLXIPL_batch1A_rep2.ctss.bed MLXIPL_batch1A_rep3.ctss.bed MLXIPL
bash ./scripts/get_coverage.sh MNX1-Start.bed MNX1_batch1A_rep1.ctss.bed MNX1_batch1A_rep2.ctss.bed MNX1_batch1A_rep3.ctss.bed MNX1
bash ./scripts/get_coverage.sh NEUROD1-Start.bed NEUROD1_batch1A_rep1.ctss.bed NEUROD1_batch1A_rep2.ctss.bed NEUROD1_batch1A_rep3.ctss.bed NEUROD1_batch1A
bash ./scripts/get_coverage.sh NEUROD1-Start.bed NEUROD1_batch2_rep1.ctss.bed NEUROD1_batch2_rep2.ctss.bed NEUROD1_batch2_rep3.ctss.bed NEUROD1_batch2
bash ./scripts/get_coverage.sh NROB2-Start.bed NROB2_batch1A_rep1.ctss.bed NROB2_batch1A_rep2.ctss.bed NROB2_batch1A_rep3.ctss.bed NROB2_batch1A
bash ./scripts/get_coverage.sh NROB2-Start.bed NROB2_batch2_rep1.ctss.bed NROB2_batch2_rep2.ctss.bed NROB2_batch2_rep3.ctss.bed NROB2_batch2
bash ./scripts/get_coverage.sh PAX6-Start.bed PAX6_batch2_rep1.ctss.bed PAX6_batch2_rep2.ctss.bed PAX6_batch2_rep3.ctss.bed PAX6
bash ./scripts/get_coverage.sh SHOX2-Start.bed SHOX2_batch2_rep1.ctss.bed SHOX2_batch2_rep2.ctss.bed SHOX2_batch2_rep3.ctss.bed SHOX2
bash ./scripts/get_coverage.sh TAF10-Start.bed TAF10_batch1A_rep1.ctss.bed TAF10_batch1A_rep2.ctss.bed TAF10_batch1A_rep3.ctss.bed TAF10
bash ./scripts/get_coverage.sh TAF9-Start.bed TAF9_batch1A_rep1.ctss.bed TAF9_batch1A_rep2.ctss.bed TAF9_batch1A_rep3.ctss.bed TAF9
bash ./scripts/get_coverage.sh TAF10-Start.bed TAF10_batch1A_rep1.ctss.bed TAF10_batch1A_rep2.ctss.bed TAF10_batch1A_rep3.ctss.bed TAF10
bash ./scripts/get_coverage.sh TAF9-Start.bed TAF9_batch1A_rep1.ctss.bed TAF9_batch1A_rep2.ctss.bed TAF9_batch1A_rep3.ctss.bed TAF9
bash ./scripts/get_coverage.sh TBP-Start.bed TBP_batch1A_rep1.ctss.bed TBP_batch1A_rep2.ctss.bed TBP_batch1A_rep3.ctss.bed TBP
bash ./scripts/get_coverage.sh TCF25-Start.bed TCF25_batch1A_rep1.ctss.bed TCF25_batch1A_rep2.ctss.bed TCF25_batch1A_rep3.ctss.bed TCF25
bash ./scripts/get_coverage.sh ATF5-Start.bed ATF5_batch1A_rep1.ctss.bed ATF5_batch1A_rep2.ctss.bed ATF5_batch1A_rep3.ctss.bed ATF5
bash ./scripts/get_coverage.sh GATA4-Start.bed GATA4_batch4_rep1.ctss.bed GATA4_batch4_rep2.ctss.bed GATA4_batch4_rep3.ctss.bed GATA4
bash ./scripts/get_coverage.sh ISL1-Start.bed ISL1_batch3_rep1.ctss.bed ISL1_batch3_rep2.ctss.bed ISL1_batch3_rep3.ctss.bed ISL1
bash ./scripts/get_coverage.sh LMX1A-Start.bed LMX1A_1_batch1A_rep1.ctss.bed LMX1A_1_batch1A_rep2.ctss.bed LMX1A_1_batch1A_rep3.ctss.bed LMX1A
bash ./scripts/get_coverage.sh PAX4-Start.bed PAX4_batch2_rep1.ctss.bed PAX4_batch2_rep2.ctss.bed PAX4_batch2_rep3.ctss.bed PAX4_batch2
bash ./scripts/get_coverage.sh PAX4-Start.bed PAX4_batch3_rep1.ctss.bed PAX4_batch3_rep2.ctss.bed PAX4_batch3_rep3.ctss.bed PAX4_batch3
bash ./scripts/get_coverage.sh PROX1-Start.bed PROX1_batch1A_rep1.ctss.bed PROX1_batch1A_rep2.ctss.bed PROX1_batch1A_rep3.ctss.bed PROX1
bash ./scripts/get_coverage.sh RFX6-Start.bed RFX6_batch1A_rep1.ctss.bed RFX6_batch1A_rep2.ctss.bed RFX6_batch1A_rep3.ctss.bed RFX6
